import { TheoryCard } from "./types";

// 30+ 条社会科学理论库。每条都按"年轻人能听懂"的口径重写。
// 覆盖：组织行为/职场、亲密关系、消费/经济、媒介/信息、城市/身份、AI/技术、普适心理学、群体行为。

export const extendedTheories: TheoryCard[] = [
  // ——— 工作 / 职场 ———
  {
    id: "boundary-work",
    name: "边界工作",
    oneSentence: "人会通过规则、语言和仪式，划出什么属于工作、什么属于生活。",
    explanatoryPower: 94,
    misuseRisk: "容易被误读成只要设边界就不用协作。",
    angle: "解释为什么一条下班消息会让人感觉私人时间被入侵。",
    everydayExample: "把手机调成勿扰，不是消失，而是告诉别人现在不在工作场域。",
    bestForTopics: ["work-boundary", "relationship-label"],
    misreadings: ["边界不是冷漠，也不是拒绝承担责任。", "边界不等于把沟通全部推给对方。"],
    counterExamples: ["真正紧急的安全问题需要例外规则。", "团队事先约定了值班机制时，回应就不再是隐形加班。"],
    sourceRefs: ["组织社会学中的边界工作", "工作家庭边界理论"],
    goldenLines: ["好的边界不是把门关上，而是告诉别人什么时候可以敲门。", "让人崩溃的不是消息，是永远默认你在线。"]
  },
  {
    id: "emotional-labor",
    name: "情绪劳动",
    oneSentence: "在工作中按规则压抑或表演情绪，本身就是一种没被算薪的劳动。",
    explanatoryPower: 90,
    misuseRisk: "不能把所有人际互动都说成情绪剥削。",
    angle: "解释服务业、客服、班委为什么累得不一样。",
    everydayExample: "明明心里烦，还要笑着说亲，下班才允许塌下来。",
    bestForTopics: ["work-boundary", "relationship-label"],
    misreadings: ["情绪劳动不是矫情。", "并非所有微笑都是被迫的。"],
    counterExamples: ["热爱这份工作的人，情绪展示成本会更低。", "短暂的角色切换不等于剥削。"],
    sourceRefs: ["Hochschild《管理之心》", "服务社会学"],
    goldenLines: ["你不是脆弱，是把没被算薪的力气用完了。", "微笑也是工时，只是没人发它的工资。"]
  },
  {
    id: "learned-helplessness",
    name: "习得性无助",
    oneSentence: "反复经历努力没用之后，人会主动放弃尝试，即使后来环境变了。",
    explanatoryPower: 86,
    misuseRisk: "不能把结构性困境直接说成心理问题。",
    angle: "解释「躺平」不只是态度，也是被训练出来的反应。",
    everydayExample: "投了 80 份简历都没回音，第 81 份点都不想点。",
    bestForTopics: ["ai-anxiety", "consumption-fatigue", "city-belonging"],
    misreadings: ["习得性无助不是懒。", "不主动尝试不等于没能力。"],
    counterExamples: ["小步反馈机制能逆转无助感。", "环境真的改变后，人也会重新行动。"],
    sourceRefs: ["Seligman 经典实验", "积极心理学"],
    goldenLines: ["不是你没意志力，是世界先训练了你别使劲。", "重新出发的第一步，是发现自己其实可以试。"]
  },
  {
    id: "social-loafing",
    name: "社会惰化",
    oneSentence: "人在群体里出力反而变少，因为责任被稀释了。",
    explanatoryPower: 80,
    misuseRisk: "不能把所有团队问题都归结于个人偷懒。",
    angle: "解释为什么大群里一句话没人接，小群秒回。",
    everydayExample: "100 人项目群里 @ 所有人，跟没说一样。",
    bestForTopics: ["work-boundary"],
    misreadings: ["不是大家都不努力，是默认别人会顶上。", "惰化不是道德问题，是结构问题。"],
    counterExamples: ["明确分工和单点责任能消解惰化。", "高凝聚力小团队不会出现。"],
    sourceRefs: ["Latané 社会心理学", "团队管理研究"],
    goldenLines: ["@ 所有人，等于没 @ 任何人。", "责任不被稀释，努力才会被看见。"]
  },

  // ——— 亲密关系 ———
  {
    id: "social-exchange",
    name: "社会交换理论",
    oneSentence: "关系会在情感、时间、支持和回报之间寻找一种可持续的平衡。",
    explanatoryPower: 86,
    misuseRisk: "不能把亲密关系完全算账化。",
    angle: "解释为什么情绪价值既是爱，也可能成为负担。",
    everydayExample: "朋友愿意听你倾诉，但也需要被看见和休息。",
    bestForTopics: ["relationship-label", "work-boundary"],
    misreadings: ["关系不是交易表。", "谈回报不是功利，而是让关系不被耗尽。"],
    counterExamples: ["照护、亲情和危机支持不能简单等价交换。", "短期失衡不等于关系失败。"],
    sourceRefs: ["社会交换理论", "情绪劳动研究"],
    goldenLines: ["亲密不是全天候客服，爱也需要可持续。", "最好的情绪价值，是双方都不用透支自己。"]
  },
  {
    id: "attachment-styles",
    name: "依恋类型",
    oneSentence: "人小时候和重要照顾者形成的回应模式，会延续到成年的亲密关系里。",
    explanatoryPower: 88,
    misuseRisk: "不要把人贴标签当成宿命。",
    angle: "解释为什么有人秒回也焦虑，有人不回也踏实。",
    everydayExample: "对方两小时没回消息，你脑补了三个版本的分手。",
    bestForTopics: ["relationship-label"],
    misreadings: ["依恋类型可以变化，不是判决书。", "不安全依恋不等于不会爱。"],
    counterExamples: ["一段稳定关系能修复早期依恋。", "成年人的反应也受当下情境影响。"],
    sourceRefs: ["Bowlby/Ainsworth 依恋理论", "成人依恋研究"],
    goldenLines: ["你不是太敏感，是身体记得那些没被回应的瞬间。", "安全感不是别人给的，是被允许慢慢长出来的。"]
  },
  {
    id: "self-disclosure",
    name: "自我披露",
    oneSentence: "亲密关系是通过双方层层互相敞开建立的，节奏不对就会出错。",
    explanatoryPower: 78,
    misuseRisk: "不要把表达欲压力强加给对方。",
    angle: "解释为什么有人聊三句就想知道你父母，有人三年也不主动开口。",
    everydayExample: "第一次约会就交代原生家庭，对方反而退一步。",
    bestForTopics: ["relationship-label"],
    misreadings: ["不是越早袒露越亲密。", "不爱说不等于不爱。"],
    counterExamples: ["危机情境下深度披露能加速亲密。", "互相匹配的克制也是一种亲密。"],
    sourceRefs: ["Altman & Taylor 社会渗透理论"],
    goldenLines: ["亲密像剥洋葱，不是一刀切到底。", "对的人会等你慢慢说，不是逼你交代。"]
  },

  // ——— 消费 / 经济 ———
  {
    id: "scarcity-mindset",
    name: "稀缺心态",
    oneSentence: "当人感觉钱、时间或机会不够时，大脑会更关注眼前压力，而不是长期选择。",
    explanatoryPower: 88,
    misuseRisk: "不能把结构性压力都说成个人心态问题。",
    angle: "解释为什么省钱口号既轻松又带着一点防御。",
    everydayExample: "看到满减时反复计算，其实是在对抗不确定感。",
    bestForTopics: ["consumption-fatigue", "ai-anxiety"],
    misreadings: ["稀缺心态不是说人不努力。", "省钱不一定是消费降级，也可能是价值排序升级。"],
    counterExamples: ["高收入人群也可能因时间稀缺而焦虑。", "长期规划需要现实资源支持，不只是心态调整。"],
    sourceRefs: ["行为经济学中的稀缺理论", "消费心理学"],
    goldenLines: ["少买不是退出生活，而是把注意力赎回来。", "真正贵的不是商品，是你被它占走的判断力。"]
  },
  {
    id: "loss-aversion",
    name: "损失厌恶",
    oneSentence: "人对失去的痛感，大约是同样获得的两倍。",
    explanatoryPower: 90,
    misuseRisk: "不能用一个偏差解释所有消费决策。",
    angle: "解释为什么「不买立省 100%」比「省钱攻略」更上头。",
    everydayExample: "丢 100 块的难受，远大于捡 100 块的开心。",
    bestForTopics: ["consumption-fatigue"],
    misreadings: ["不是人不理性，是大脑天生就这样。", "厌恶损失不等于胆小。"],
    counterExamples: ["明确的长期收益能压过即时损失感。", "不同文化下系数也会不同。"],
    sourceRefs: ["Kahneman & Tversky 前景理论"],
    goldenLines: ["你不是抠门，是大脑对失去更敏感。", "最贵的损失，是错过自己原本的判断力。"]
  },
  {
    id: "conspicuous-consumption",
    name: "炫耀性消费",
    oneSentence: "买东西不只是为了用，也是为了向某个群体发出信号。",
    explanatoryPower: 84,
    misuseRisk: "不要居高临下批判别人花钱方式。",
    angle: "解释为什么「精致穷」不是矛盾，而是一种身份费用。",
    everydayExample: "工资刚发就买拿铁，喝的是身份不是咖啡。",
    bestForTopics: ["consumption-fatigue", "city-belonging"],
    misreadings: ["不是所有消费都是炫耀。", "信号也可以发给自己看。"],
    counterExamples: ["匿名消费几乎不带身份信号。", "收藏品有真实使用价值。"],
    sourceRefs: ["Veblen《有闲阶级论》"],
    goldenLines: ["很多东西买的不是物，是「我是哪种人」的入场券。", "便宜的东西，有时候是身份税最高的。"]
  },
  {
    id: "hedonic-treadmill",
    name: "享乐适应",
    oneSentence: "人很快会把新得到的快乐变成默认值，于是不停追下一个。",
    explanatoryPower: 82,
    misuseRisk: "不要用它劝人接受所有不满意。",
    angle: "解释为什么换工作三个月就开始失望。",
    everydayExample: "新手机用一周就觉得理所当然，立刻看下一款。",
    bestForTopics: ["consumption-fatigue", "ai-anxiety"],
    misreadings: ["不是你不知足，是适应是默认设置。", "享乐适应不否认快乐本身。"],
    counterExamples: ["关系深度、意义感不容易适应化。", "感激练习能减缓适应速度。"],
    sourceRefs: ["Brickman 享乐适应研究", "积极心理学"],
    goldenLines: ["快乐不是被找到，是被维护出来的。", "你不是难以满足，是大脑总在重新校准。"]
  },

  // ——— 城市 / 身份 / 阶层 ———
  {
    id: "social-comparison",
    name: "社会比较",
    oneSentence: "人会通过和别人比较来判断自己的位置，工具越多，比较对象也越多。",
    explanatoryPower: 82,
    misuseRisk: "不能把技术变化造成的真实压力简化成嫉妒。",
    angle: "解释 AI 工具越多，为什么人反而更怕落后。",
    everydayExample: "收藏 100 个工具后，真正让人焦虑的是别人好像已经用它赚钱了。",
    bestForTopics: ["ai-anxiety", "city-belonging"],
    misreadings: ["比较不是虚荣，是人判断位置的默认方式。", "焦虑不总是个人脆弱，也可能是竞争规则改变。"],
    counterExamples: ["清楚的学习目标能降低比较带来的噪音。", "某些岗位的 AI 压力是真实技能迁移问题。"],
    sourceRefs: ["社会比较理论", "技术采用与身份焦虑"],
    goldenLines: ["你焦虑的不是工具太多，而是排行榜突然变长了。", "工具会更新，判断力才是你的操作系统。"]
  },
  {
    id: "reference-group",
    name: "参照群体",
    oneSentence: "一个人怎么评价自己的生活，常常取决于他拿谁当参照。",
    explanatoryPower: 84,
    misuseRisk: "不能忽视收入、家庭和城市资源的现实差异。",
    angle: "解释为什么换城市像是在换一套人生评分表。",
    everydayExample: "在一线城市觉得自己慢，换到另一座城市后发现生活节奏可以重新定义。",
    bestForTopics: ["city-belonging", "consumption-fatigue"],
    misreadings: ["换参照不是逃避现实。", "参照群体会影响感受，但不能替代收入和机会。"],
    counterExamples: ["职业高集中行业仍然需要城市资源。", "家庭照护和医疗教育会改变城市选择。"],
    sourceRefs: ["参照群体理论", "城市社会学与生活方式研究"],
    goldenLines: ["换一座城市，有时候是在换一张人生计分表。", "不是你跑得慢，是你可能站错了赛道。"]
  },
  {
    id: "relative-deprivation",
    name: "相对剥夺",
    oneSentence: "人感到被亏待，不是和昨天的自己比，而是和「应该和我差不多的人」比。",
    explanatoryPower: 86,
    misuseRisk: "不要用它否认绝对贫困和真实差距。",
    angle: "解释为什么收入涨了反而更不开心。",
    everydayExample: "涨薪 10%，但发现同学涨了 30%，心情瞬间塌。",
    bestForTopics: ["city-belonging", "consumption-fatigue", "ai-anxiety"],
    misreadings: ["相对剥夺不是矫情。", "不是收入低就一定剥夺感强。"],
    counterExamples: ["参考组改变后剥夺感会重置。", "极端贫困是绝对问题，不是相对问题。"],
    sourceRefs: ["Stouffer 相对剥夺研究", "社会运动学"],
    goldenLines: ["不是你赚得不够，是你看到了不该比的人。", "幸福往往不是绝对，是「我们这群人」的中位数。"]
  },
  {
    id: "cultural-capital",
    name: "文化资本",
    oneSentence: "审美、谈吐、知识储备也是一种资本，能换来机会和身份认同。",
    explanatoryPower: 88,
    misuseRisk: "不要把它说成只要看几本书就能跨阶层。",
    angle: "解释为什么职场里同样能力的人被对待方式不同。",
    everydayExample: "面试聊到爱看的展，对方眼神瞬间换了一种。",
    bestForTopics: ["city-belonging", "ai-anxiety"],
    misreadings: ["文化资本不是装。", "不是有学历就有文化资本。"],
    counterExamples: ["产业变化让某些文化资本快速贬值。", "草根审美在新平台上反而是优势。"],
    sourceRefs: ["布尔迪厄《区分》"],
    goldenLines: ["你以为是聊天，其实是在交换隐形货币。", "审美不是装饰，是你能进哪扇门的钥匙之一。"]
  },

  // ——— 媒介 / 信息 / 认知偏差 ———
  {
    id: "framing-effect",
    name: "框架效应",
    oneSentence: "同一件事被放进不同表达框架里，会触发完全不同的判断。",
    explanatoryPower: 78,
    misuseRisk: "不能把事实争议只归因于话术包装。",
    angle: "解释为什么「拒绝加班」和「保护协作规则」听起来像两件事。",
    everydayExample: "同样是不回消息，说成失联和说成非工作时间，感受完全不同。",
    bestForTopics: ["work-boundary", "consumption-fatigue", "city-belonging"],
    misreadings: ["框架不是洗白事实。", "换表达不能代替解决真实问题。"],
    counterExamples: ["当事实足够明确时，框架影响会下降。", "涉及权利侵害时不能只讨论表达方式。"],
    sourceRefs: ["认知心理学中的框架效应", "传播学议题框架"],
    goldenLines: ["很多争论不是答案不同，而是题目被写成了两套。", "换一个框架，不是换立场，是先看见问题长什么样。"]
  },
  {
    id: "availability-heuristic",
    name: "可得性启发",
    oneSentence: "人判断一件事多严重，常常靠脑里能不能马上想到例子，而不是真实概率。",
    explanatoryPower: 82,
    misuseRisk: "不要用它否定人的真实担忧。",
    angle: "解释为什么刷一晚上小红书就觉得世界要塌。",
    everydayExample: "看完三个翻车视频，觉得整个行业都不行了。",
    bestForTopics: ["ai-anxiety", "consumption-fatigue"],
    misreadings: ["不是想得到就一定错。", "情绪反应也是判断材料。"],
    counterExamples: ["数据训练能纠正可得性偏差。", "媒体放大不等于事实不存在。"],
    sourceRefs: ["Kahneman & Tversky 启发与偏差"],
    goldenLines: ["你不是焦虑过度，是算法把同一个故事讲了 30 遍。", "印象 ≠ 概率，记住的不一定是常见的。"]
  },
  {
    id: "echo-chamber",
    name: "回音室",
    oneSentence: "在算法推荐里，你越同意什么，就越被喂同意什么，听不到反对声。",
    explanatoryPower: 86,
    misuseRisk: "不要用它指控所有意见一致的群体。",
    angle: "解释为什么你和爸妈刷同一款 App 看到的世界完全不同。",
    everydayExample: "你刷的全是 AI 进步，对方刷的全是 AI 失业。",
    bestForTopics: ["ai-anxiety", "city-belonging"],
    misreadings: ["回音室不只是个人选择，也是平台机制。", "走出回音室不等于必须立刻反对。"],
    counterExamples: ["主动订阅异见信息会减弱回音效应。", "线下生活仍然有不同声音。"],
    sourceRefs: ["Sunstein《回音室》", "算法社会学"],
    goldenLines: ["你不是和别人吵不通，是你们刷的根本不是同一个世界。", "拓宽眼界，比说服别人更重要。"]
  },
  {
    id: "third-person-effect",
    name: "第三人效应",
    oneSentence: "人总觉得别人比自己更容易被广告、谣言或情绪带节奏。",
    explanatoryPower: 76,
    misuseRisk: "不要用它否认舆论确实会影响他人。",
    angle: "解释为什么我们都说自己「清醒」，但都怕别人不清醒。",
    everydayExample: "你说算法不影响你，但很担心爸妈被骗。",
    bestForTopics: ["ai-anxiety", "consumption-fatigue"],
    misreadings: ["不是觉得别人傻，是高估了自己。", "效应存在不代表所有人都被影响相同。"],
    counterExamples: ["专业训练后人确实更不易被影响。", "亲身经历事件能改变判断。"],
    sourceRefs: ["Davison 第三人效应"],
    goldenLines: ["你以为你最清醒，可能就是最危险的开始。", "真正的影响，从「这事跟我无关」开始。"]
  },
  {
    id: "spiral-of-silence",
    name: "沉默的螺旋",
    oneSentence: "当人觉得自己的看法是少数时，会越来越不敢说，少数感被进一步放大。",
    explanatoryPower: 80,
    misuseRisk: "不能用它替任何主流意见辩护。",
    angle: "解释为什么评论区看似一边倒，私聊却完全不一样。",
    everydayExample: "群里没人反对，直到你私聊朋友才发现一半人都不同意。",
    bestForTopics: ["work-boundary", "relationship-label"],
    misreadings: ["不说不等于同意。", "螺旋可以被打断。"],
    counterExamples: ["小群体保护下，少数派会更敢发声。", "事实变化能让螺旋反转。"],
    sourceRefs: ["Noelle-Neumann 沉默的螺旋"],
    goldenLines: ["让一个观点消失，不需要禁声，只需要让人觉得「就我这样想」。", "勇敢一点，可能你不是少数，只是先开口的那个。"]
  },

  // ——— AI / 技术 ———
  {
    id: "matthew-effect",
    name: "马太效应",
    oneSentence: "已经有的会被加倍给，已经少的会被加倍拿走。",
    explanatoryPower: 84,
    misuseRisk: "不要用它做宿命论。",
    angle: "解释为什么 AI 时代「会用工具的人」拉得更开。",
    everydayExample: "粉丝多的账号涨粉更快，0 粉的视频根本没分发。",
    bestForTopics: ["ai-anxiety", "city-belonging"],
    misreadings: ["不是马太就一定不可逆。", "起点低不等于一定输。"],
    counterExamples: ["新平台早期会重置马太。", "政策与平台机制能修正分配。"],
    sourceRefs: ["Merton 科学社会学", "网络效应研究"],
    goldenLines: ["世界不是公平的赛跑，是带着分数往前跑。", "找到刚开始计分的赛道，比拼命追老榜更重要。"]
  },
  {
    id: "skill-biased-tech-change",
    name: "技能偏向型技术变迁",
    oneSentence: "新技术不是平均替代所有工作，而是奖励某一类技能、惩罚另一类。",
    explanatoryPower: 88,
    misuseRisk: "不要用它劝人立刻转行。",
    angle: "解释为什么同样在用 AI，有人涨薪有人被替代。",
    everydayExample: "一样写文案，能给 AI 写好 prompt 的人，产出 5 倍。",
    bestForTopics: ["ai-anxiety"],
    misreadings: ["不是技术偏爱年轻人，是偏爱某些技能。", "被偏向不等于被注定。"],
    counterExamples: ["不同行业偏向方向不同。", "互补性技能（信任、审美）反而升值。"],
    sourceRefs: ["劳动经济学：技能偏向技术变迁理论"],
    goldenLines: ["AI 不会让你失业，但会让你重新报价。", "新技术不淘汰人，淘汰的是只会一种动作的人。"]
  },
  {
    id: "automation-paradox",
    name: "自动化悖论",
    oneSentence: "工具越自动，留给人做的判断反而越关键、越累。",
    explanatoryPower: 80,
    misuseRisk: "不能用来反对自动化本身。",
    angle: "解释为什么用了 AI 反而更累。",
    everydayExample: "AI 草稿出得快，但你要花更多时间核对、改口吻、删错。",
    bestForTopics: ["ai-anxiety", "work-boundary"],
    misreadings: ["不是自动化没用。", "累不一定等于做错了选择。"],
    counterExamples: ["流程清晰时自动化能真正减负。", "判断本身可以被训练成肌肉记忆。"],
    sourceRefs: ["人因工程：自动化悖论"],
    goldenLines: ["AI 干掉了苦力活，留下的全是判断题。", "省下的不是时间，是把时间留给更难的事。"]
  },

  // ——— 普适心理学 / 自我 ———
  {
    id: "self-determination",
    name: "自我决定理论",
    oneSentence: "人长期愿意做一件事，需要三件事：自主、胜任、连接。",
    explanatoryPower: 90,
    misuseRisk: "不要把它简化成「自由就行」。",
    angle: "解释为什么钱给到位还是想离职。",
    everydayExample: "工资不错，但每天被微管理，三个月就熄火。",
    bestForTopics: ["work-boundary", "ai-anxiety"],
    misreadings: ["自主不是放任。", "胜任感不是靠夸出来的。"],
    counterExamples: ["短期高强度任务可以违反三要素。", "外在动机也能催生内在动机。"],
    sourceRefs: ["Deci & Ryan 自我决定理论"],
    goldenLines: ["让人留下的不是工资，是能不能做自己。", "持续的动力，不是被推着走，是被允许往前走。"]
  },
  {
    id: "dunning-kruger",
    name: "邓宁-克鲁格效应",
    oneSentence: "能力越低的人，越容易高估自己；真懂的人反而更谨慎。",
    explanatoryPower: 78,
    misuseRisk: "不要用它嘲讽具体的人。",
    angle: "解释为什么半懂的人最敢下结论。",
    everydayExample: "刚学 AI 三天的人比研究员还敢预测未来。",
    bestForTopics: ["ai-anxiety"],
    misreadings: ["效应不是说自信都是假的。", "谨慎不等于真懂。"],
    counterExamples: ["有些领域反馈即时，效应会消退。", "情境复杂时所有人都会偏差。"],
    sourceRefs: ["Dunning & Kruger 1999"],
    goldenLines: ["真懂的人，先承认自己不懂。", "最危险的，不是不知道，是以为自己知道。"]
  },
  {
    id: "flow-theory",
    name: "心流",
    oneSentence: "当任务难度刚好略高于你的能力，人会进入忘我专注的状态。",
    explanatoryPower: 84,
    misuseRisk: "不要把它当成解决一切焦虑的灵丹。",
    angle: "解释为什么刷手机两小时反而更累，深度工作两小时反而清醒。",
    everydayExample: "写一段对的代码到忘记吃饭，时间像被压缩了。",
    bestForTopics: ["ai-anxiety", "work-boundary"],
    misreadings: ["心流不只在工作里。", "进入心流不是天赋，是设计。"],
    counterExamples: ["任务太难或太简单都进不去。", "干扰过多的环境直接破坏。"],
    sourceRefs: ["Csikszentmihalyi 心流"],
    goldenLines: ["你不是没专注力，是没遇到刚刚好难的事。", "真正的休息，有时候是更投入地做点什么。"]
  },
  {
    id: "identity-foreclosure",
    name: "身份过早封闭",
    oneSentence: "人没怎么探索就接受了一个身份，看似稳定，其实更脆弱。",
    explanatoryPower: 80,
    misuseRisk: "不要把任何明确选择都说成封闭。",
    angle: "解释为什么从小被规划好的人到了 30 岁突然崩。",
    everydayExample: "一直被父母安排到 25 岁，第一次被问「你想做什么」哑口无言。",
    bestForTopics: ["city-belonging", "ai-anxiety"],
    misreadings: ["不是有明确目标就是封闭。", "迷茫不一定是健康的。"],
    counterExamples: ["对的环境会鼓励再探索。", "稳定身份在危机时是支点。"],
    sourceRefs: ["Marcia 身份状态理论"],
    goldenLines: ["你不是迷茫，是终于轮到你为自己探索。", "稳定如果没经过怀疑，往往一推就倒。"]
  },

  // ——— 群体行为 ———
  {
    id: "bystander-effect",
    name: "旁观者效应",
    oneSentence: "在场的人越多，每个人出手帮忙的概率反而越低。",
    explanatoryPower: 82,
    misuseRisk: "不要用它替不作为辩护。",
    angle: "解释为什么大群里求助没人理。",
    everydayExample: "100 人群求助借充电宝，无人响应。",
    bestForTopics: ["work-boundary", "relationship-label"],
    misreadings: ["不是人冷漠，是责任被扩散了。", "效应可以被打破。"],
    counterExamples: ["明确指定一个人就会立刻有响应。", "小群体凝聚力高时不会出现。"],
    sourceRefs: ["Darley & Latané 旁观者效应"],
    goldenLines: ["求助要点名，不要广播。", "大家都看见，等于没人在看。"]
  },
  {
    id: "moral-licensing",
    name: "道德许可",
    oneSentence: "做了一件被认为「好」的事之后，人会允许自己做一件相反的事。",
    explanatoryPower: 76,
    misuseRisk: "不要用它否定所有善行。",
    angle: "解释为什么早上跑了 5 公里，晚上奖励一顿火锅+奶茶。",
    everydayExample: "今天读书 1 小时，刷剧 3 小时心安理得。",
    bestForTopics: ["consumption-fatigue", "work-boundary"],
    misreadings: ["不是所有奖励都是许可。", "适度奖励帮维持习惯。"],
    counterExamples: ["把行为定义为身份而非任务能避免许可。", "长期目标能压过短期许可。"],
    sourceRefs: ["Monin & Miller 道德许可"],
    goldenLines: ["奖励小心，别让它把你今天努力的全抵消了。", "你不是没自律，是给自己开了太多许可证。"]
  },
  {
    id: "halo-effect",
    name: "光环效应",
    oneSentence: "对一个人或品牌一个方面的好印象，会自动扩散到其他方面。",
    explanatoryPower: 78,
    misuseRisk: "不要用它否定真实的优秀。",
    angle: "解释为什么一个博主长得好看，专业建议也容易被信。",
    everydayExample: "颜值高的人发财经内容，互动比同类高 3 倍。",
    bestForTopics: ["consumption-fatigue", "ai-anxiety"],
    misreadings: ["光环不是骗术。", "看见光环不等于盲信。"],
    counterExamples: ["专业领域里数据反馈能减弱光环。", "用户长期使用后光环会褪色。"],
    sourceRefs: ["Thorndike 光环效应"],
    goldenLines: ["你买的有时候不是产品，是你脑里的那道光。", "看穿光环，不是变冷漠，是分得清买的是什么。"]
  },
  {
    id: "social-proof",
    name: "社会认同",
    oneSentence: "在不确定时，人会模仿大多数人的选择来降低决策成本。",
    explanatoryPower: 84,
    misuseRisk: "不要把跟风全说成没主见。",
    angle: "解释为什么榜单一出来你就想点进去。",
    everydayExample: "餐厅门口排队的，一定要排一下才放心。",
    bestForTopics: ["consumption-fatigue", "ai-anxiety"],
    misreadings: ["跟随多数不一定错。", "不跟风也不等于独立思考。"],
    counterExamples: ["专业判断能压过社会认同。", "信号造假时多数会一起错。"],
    sourceRefs: ["Cialdini《影响力》", "社会心理学"],
    goldenLines: ["排队不是质量保证，是对抗不确定的便宜药。", "你跟的不是潮流，是不愿一个人承担选错。"]
  },
  {
    id: "imagined-community",
    name: "想象的共同体",
    oneSentence: "人和素不相识的陌生人产生「我们」感，是被语言、媒介和仪式建构出来的。",
    explanatoryPower: 82,
    misuseRisk: "不要用它否定真实归属。",
    angle: "解释为什么同看一个直播会觉得「我们这代人」。",
    everydayExample: "深夜刷到同款苦笑梗，瞬间觉得不孤独。",
    bestForTopics: ["city-belonging", "relationship-label"],
    misreadings: ["想象不是假的。", "共同体也可以是排他的。"],
    counterExamples: ["危机时刻线下行动会重塑共同体。", "代际差异会切断「我们」感。"],
    sourceRefs: ["Anderson《想象的共同体》"],
    goldenLines: ["你以为的「我们这一代」，是被同一段视频共同养大的。", "孤独的解药，有时是一段你以为只属于你的金句。"]
  },
  {
    id: "weak-ties",
    name: "弱关系的力量",
    oneSentence: "新机会和新信息，往往不是从最熟的人那里来，而是从泛泛之交那里来。",
    explanatoryPower: 80,
    misuseRisk: "不要把它解读成不需要深交。",
    angle: "解释为什么换工作往往是某个不熟的群友推过来的。",
    everydayExample: "微信里 5 年没说话的同学，发来一个内推。",
    bestForTopics: ["work-boundary", "city-belonging", "ai-anxiety"],
    misreadings: ["弱关系不是社交工具人。", "强关系仍然是支撑你的核心。"],
    counterExamples: ["危机时强关系才扛得住。", "纯线上弱关系信任成本高。"],
    sourceRefs: ["Granovetter 弱关系理论"],
    goldenLines: ["命运的转弯，常常是从一个你不熟的人那里来的。", "维护弱关系，不是势利，是给未来留下入口。"]
  }
];
